### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by Xinzi526** [csl-ajou/DeepPlan#3]
Hello! I'm getting an error when running the plan.py script. 

```shell
Traceback (most recent call last):
  File "/GOODDATA/wangxinyu/DeepPlan/plan.py", line 459, in <module>
    generate_plan(model, input_data, output_dir_path, do_profile, do_trace)
  File "/GOODDATA/wangxinyu/DeepPlan/plan.py", line 368, in generate_plan
    layers = dump_profile_info(model, x, profile_info_path)
  File "/GOODDATA/wangxinyu/DeepPlan/plan.py", line 195, in dump_profile_info
    size += np.prod(np.array(buf.size())) * 4
AttributeError: 'NoneType' object has no attribute 'size'
``` 
While going through the code, I noticed a potential concern that I would like to discuss.

In the following code snippet:
```python
for i, layer in enumerate(_layers):
    size = 0
    for key, param in layer._parameters.items():
        if param is not None:
            size += np.prod(np.array(param.size())) * 4
    for key, buf in layer._buffers.items():
        if buf is not None:
            size += np.prod(np.array(param.size())) * 4
``` 
The same code 'size += np.prod(np.array(param.size())) * 4' appears twice, should 'param' in the last line be replaced with 'buf'?

**Comment by JinuJeong** [comment]
Thank you for pointing out the incorrect code. As you've mentioned, the code should be changed from 'parm' to 'buf'. That was my oversight. However, I'm uncertain as to why the error you mentioned occurs, especially since [line 194](https://github.com/csl-ajou/DeepPlan/blob/main/plan.py#L194) already checks the type of buf.

**Comment by Xinzi526** [comment]
I'm very interested in your project, and I encountered this issue while trying to run the 'llama_7b' model using it.

**Comment by Xinzi526** [comment]
Well, when running the existing models listed in 'model_list', I haven't encountered this issue. I have already added the 'llama' model to the list, but now, although Model config is created, I'm facing a "RuntimeError: CUDA out of memory" when generating the trace module. 

The error message states:
```shell
2023-08-05 03:04:44,848:INFO:Creating trace module
/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:482: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if input_shape[-1] > 1:
/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:53: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mask = torch.full((tgt_len, tgt_len), torch.tensor(torch.finfo(dtype).min))
/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:115: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if seq_len > self.max_seq_len_cached:
/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /GOODDATA/wangxinyu/pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:238: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_weights.size() != (bsz, self.num_heads, q_len, kv_seq_len):
/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:245: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attention_mask.size() != (bsz, 1, q_len, kv_seq_len):
/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:250: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  attn_weights = torch.max(attn_weights, torch.tensor(torch.finfo(attn_weights.dtype).min))
/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:256: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if attn_output.size() != (bsz, self.num_heads, q_len, self.head_dim):
Traceback (most recent call last):
  File "/GOODDATA/wangxinyu/DeepPlan/plan.py", line 454, in <module>
    generate_plan(model, input_data, output_dir_path, do_profile, do_trace)
  File "/GOODDATA/wangxinyu/DeepPlan/plan.py", line 430, in generate_plan
    trace_module = generate_trace_module(model, x)
  File "/GOODDATA/wangxinyu/DeepPlan/plan.py", line 346, in generate_trace_module
    trace_module = torch.jit.trace(model, x)
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/torch/jit/_trace.py", line 735, in trace
    return trace_module(
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/torch/jit/_trace.py", line 952, in trace_module
    module._c._create_method_from_trace(
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1065, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1053, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 621, in forward
    layer_outputs = decoder_layer(
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1065, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1053, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 316, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1065, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1053, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/GOODDATA/wangxinyu/anaconda3/envs/deepplan_clone/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 236, in forward
    attn_weights = torch.matmul(query_states, key_states.transpose(2, 3)) / math.sqrt(self.head_dim)
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 31.75 GiB total capacity; 30.31 GiB already allocated; 419.50 MiB free; 30.31 GiB reserved in total by PyTorch)
```
I'm unsure about the specific source of this issue and wanted to seek your guidance.

Given your expertise, I would appreciate any suggestions or recommendations you might have to address this problem. I'm actively looking into potential solutions, but your insights could significantly expedite the troubleshooting process.

**Comment by JinuJeong** [comment]
If you're using the `llama-7b` model, the memory usage might exceed your GPU memory capacity (30GB). Our project only supports the FP32 data type. With FP32, the model size is approximately 28GB.

**Comment by Xinzi526** [comment]
emmmmm... If I would like this project to support FP16 or int8, could you kindly indicate which specific components might necessitate some modifications?

**Comment by JinuJeong** [comment]
You are able to easily use the FP16 model by converting the weights and input data from FP32 to FP16.
For example,
`
model = Model()
model.half()

input_data = input_data.half()

output = model(input_data)
`
If you would like the plan.py to support FP16, you should additionally insert the type casting in main() function.
After making this adjustment and running `plan.py`, the FP16 model trace file will be generated.
If you plan to use the experiment scripts for the FP16 model, you will need additional type-casting works for the input data in benchmark code or server/client code.
